디버깅/3차 pjt 디버깅/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

디버깅/3차 pjt 디버깅/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

디버깅/3차 pjt 디버깅/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
]

디버깅/3차 pjt 디버깅/pjt09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

디버깅/3차 pjt 디버깅/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <nav>
      {% if user.is_authenticated %}
      <h3>Hello, {{ user.username }}</h3>
      <a href="{% url 'accounts:profile' user %}">내 프로필<a>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Logout">
      </form>
      <a href="{% url 'movies:index'%}">Movie</a>
      <a href="{% url 'community:index'%}">Community</a>
      <a href="{% url 'community:create'%}">New Review</a>
      {% else %}
      <a href="{% url 'accounts:signup' %}">Signup</a>
      <a href="{% url 'accounts:login' %}">Login</a>
      {% endif %}
    </nav>
    {% block content %}
    {% endblock %}
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  {% block script %}
  {% endblock script %}

</body>
</html>

디버깅/3차 pjt 디버깅/templates/c.html
{% block script %}
<script>
  // form, csrftoken
  const form = document.querySelector('#follow-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  // form에 event 처리
  form.addEventListener('submit', (event)=>{
    event.preventDefault()
    const userId = event.target.dataset.userId
  // axois
  axios({
    method: 'post',
    url: `http://127.0.0.1:8000/accounts/${userId}/follow/`,
    headers: {'X-CSRFToken' : csrftoken}
  })
  // then
    .then(response => {
      //console.log(response)
      const followed = response.data.followed
      const followButton = document.querySelector(`#followBtn-${userId}`)
      if (followed) {
        followButton.innerText = '언팔로우'
      }
      else {
        followButton.innerText = '팔로우'
      }
      const followersCount = response.data.followers_count
      const followingsCount = response.data.followings_count
      const friendsP = document.querySelector('.friends')
      friendsP.innerText = `팔로잉 : ${followingsCount} / 팔로워 : ${followersCount}`
    })

  })
  
</script>
{% endblock script %}


{% block script %}
<script>
  // form, csrftoken
  const forms = document.querySelectorAll('.like-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  forms.forEach(form => {
    form.addEventListener('submit', (event)=>{
      event.preventDefault()
      //console.log(event)
      const reviewId = event.target.dataset.reviewId
      
      axios ({
        method : 'post',
        url : `http://127.0.0.1:8000/community/${reviewId}/like/`,
        headers : { 'X-CSRFToken' : csrftoken},
      })
      .then(response => {
        //console.log(response)
        const liked = response.data.liked
        const likeBtn = document.querySelector(`#like-${reviewId}`)
        if (liked) {
          likeBtn.innerText = '좋아요 취소'
        }
        else {
          likeBtn.innerText = '좋아요'
        }
        const count = response.data.count
        const likeCount = document.querySelector(`#likecount-${reviewId}`)
        likeCount.innerText = `${count} 명이 이 글을 좋아합니다.`
      })
    })
    
  })
</script>
{% endblock script %}